<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJW2Q36M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJW2Q36M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJW2Q36M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJW2Q36M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJW2Q36M\App_KernelDevDebugContainer([
    'container.build_hash' => 'JW2Q36M',
    'container.build_id' => 'f89c99f9',
    'container.build_time' => 1592907183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJW2Q36M');
