<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'enterprise_edit' => [['enterprise'], ['_controller' => 'App\\Controller\\EnterpriseController::editEnterprise'], [], [['variable', '/', '[^/]++', 'enterprise', true], ['text', '/api/enterprises']], [], []],
    'add_identified_case' => [[], ['_controller' => 'App\\Controller\\IdentifiedCaseController::addIdentifiedCase'], [], [['text', '/api/identified-case']], [], []],
    'show_list_identified_case' => [[], ['_controller' => 'App\\Controller\\IdentifiedCaseController::listIdentifiedCase'], [], [['text', '/api/identified-case']], [], []],
];
