<?php

namespace ContainerJW2Q36M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdentifiedCaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\IdentifiedCaseController' shared autowired service.
     *
     * @return \App\Controller\IdentifiedCaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/IdentifiedCaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/IdentifiedCaseHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Transformer/IdentifiedCaseTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Serializer/ValidationErrorSerializer.php';

        $container->services['App\\Controller\\IdentifiedCaseController'] = $instance = new \App\Controller\IdentifiedCaseController(new \App\Services\IdentifiedCaseHandler(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['validator'] ?? $container->load('getValidatorService')), new \App\Transformer\IdentifiedCaseTransformer()), ($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')), ($container->privates['App\\Serializer\\ValidationErrorSerializer'] ?? ($container->privates['App\\Serializer\\ValidationErrorSerializer'] = new \App\Serializer\ValidationErrorSerializer())));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\IdentifiedCaseController', $container));

        return $instance;
    }
}
