<?php

namespace ContainerJW2Q36M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntellstApiCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\IntellstApiCommand' shared autowired service.
     *
     * @return \App\Command\IntellstApiCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/IntellstApiCommand.php';

        $container->privates['App\\Command\\IntellstApiCommand'] = $instance = new \App\Command\IntellstApiCommand();

        $instance->setName('app:intellst-api');

        return $instance;
    }
}
